name: ğ™¨ğ™ğ™¡ğ™–ğ™©ğ™§ğ™ğ™­-ğ™¢ğ™™
services:
  - name: megalodon-md-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin


      
